import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "@/app/[locale]/globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound as nextNotFound } from "next/navigation";
import { routing } from "@/i18n/routing";


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  let messages;
  try {
    messages = (await import(`../../../../messages/${locale}.json`)).default;
  } catch {
    notFound();
  }

  
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}


function notFound() {
  nextNotFound();
}

